Repository nextcloud/docker, pull requests merged in 2018-10, with the labels that each got.

#479 Add some dummy hash for uncommited Dockerfiles
  generate-stackbrew-library.sh
Labels: enhancement

#478 Use exclude file for the updater
  12.0/apache/Dockerfile
  12.0/apache/entrypoint.sh
  12.0/apache/upgrade.exclude
  12.0/fpm-alpine/Dockerfile
  12.0/fpm-alpine/entrypoint.sh
  12.0/fpm-alpine/upgrade.exclude
  12.0/fpm/Dockerfile
  12.0/fpm/entrypoint.sh
  12.0/fpm/upgrade.exclude
  13.0/apache/Dockerfile
  13.0/apache/entrypoint.sh
  13.0/apache/upgrade.exclude
  13.0/fpm-alpine/Dockerfile
  13.0/fpm-alpine/entrypoint.sh
  13.0/fpm-alpine/upgrade.exclude
  13.0/fpm/Dockerfile
  13.0/fpm/entrypoint.sh
  13.0/fpm/upgrade.exclude
  14.0/apache/Dockerfile
  14.0/apache/entrypoint.sh
  14.0/apache/upgrade.exclude
  14.0/fpm-alpine/Dockerfile
  14.0/fpm-alpine/entrypoint.sh
  14.0/fpm-alpine/upgrade.exclude
  14.0/fpm/Dockerfile
  14.0/fpm/entrypoint.sh
  14.0/fpm/upgrade.exclude
  Dockerfile-alpine.template
  Dockerfile-debian.template
  docker-entrypoint.sh
  update.sh
  upgrade.exclude
Labels: enhancement, image

#480 added retry loop and decreased sleep time
  12.0/apache/entrypoint.sh
  12.0/fpm-alpine/entrypoint.sh
  12.0/fpm/entrypoint.sh
  13.0/apache/entrypoint.sh
  13.0/fpm-alpine/entrypoint.sh
  13.0/fpm/entrypoint.sh
  14.0/apache/entrypoint.sh
  14.0/fpm-alpine/entrypoint.sh
  14.0/fpm/entrypoint.sh
  docker-entrypoint.sh
Labels: enhancement, image

#500 add a mechanism to set trusted domains on install
  12.0/apache/entrypoint.sh
  12.0/fpm-alpine/entrypoint.sh
  12.0/fpm/entrypoint.sh
  13.0/apache/entrypoint.sh
  13.0/fpm-alpine/entrypoint.sh
  13.0/fpm/entrypoint.sh
  14.0/apache/entrypoint.sh
  14.0/fpm-alpine/entrypoint.sh
  14.0/fpm/entrypoint.sh
  README.md
  docker-entrypoint.sh
Labels: enhancement, image

#515 Add NEXTCLOUD_UPDATE for containers started with non-default commands
  .examples/README.md
  .examples/dockerfiles/cron/apache/Dockerfile
  .examples/dockerfiles/cron/fpm/Dockerfile
  .travis/test-example-dockerfiles.sh
  12.0/apache/entrypoint.sh
  12.0/fpm-alpine/entrypoint.sh
  12.0/fpm/entrypoint.sh
  13.0/apache/entrypoint.sh
  13.0/fpm-alpine/entrypoint.sh
  13.0/fpm/entrypoint.sh
  14.0/apache/entrypoint.sh
  14.0/fpm-alpine/entrypoint.sh
  14.0/fpm/entrypoint.sh
  README.md
  docker-entrypoint.sh
Labels: bug, image
