Repository nextcloud/docker, pull requests merged in 2018-03, with the labels that each got.

#283 Manually run update.sh
  .travis.yml
  11.0-rc/apache/Dockerfile
  11.0-rc/apache/config/apache-pretty-urls.config.php
  11.0-rc/apache/config/apcu.config.php
  11.0-rc/apache/config/apps.config.php
  11.0-rc/apache/config/autoconfig.php
  11.0-rc/apache/cron.sh
  11.0-rc/apache/entrypoint.sh
  11.0-rc/fpm-alpine/Dockerfile
  11.0-rc/fpm-alpine/config/apcu.config.php
  11.0-rc/fpm-alpine/config/apps.config.php
  11.0-rc/fpm-alpine/config/autoconfig.php
  11.0-rc/fpm-alpine/cron.sh
  11.0-rc/fpm-alpine/entrypoint.sh
  11.0-rc/fpm/Dockerfile
  11.0-rc/fpm/config/apcu.config.php
  11.0-rc/fpm/config/apps.config.php
  11.0-rc/fpm/config/autoconfig.php
  11.0-rc/fpm/cron.sh
  11.0-rc/fpm/entrypoint.sh
  12.0-rc/apache/Dockerfile
  12.0-rc/apache/config/apache-pretty-urls.config.php
  12.0-rc/apache/config/apcu.config.php
  12.0-rc/apache/config/apps.config.php
  12.0-rc/apache/config/autoconfig.php
  12.0-rc/apache/cron.sh
  12.0-rc/apache/entrypoint.sh
  12.0-rc/fpm-alpine/Dockerfile
  12.0-rc/fpm-alpine/config/apcu.config.php
  12.0-rc/fpm-alpine/config/apps.config.php
  12.0-rc/fpm-alpine/config/autoconfig.php
  12.0-rc/fpm-alpine/cron.sh
  12.0-rc/fpm-alpine/entrypoint.sh
  12.0-rc/fpm/Dockerfile
  12.0-rc/fpm/config/apcu.config.php
  12.0-rc/fpm/config/apps.config.php
  12.0-rc/fpm/config/autoconfig.php
  12.0-rc/fpm/cron.sh
  12.0-rc/fpm/entrypoint.sh
  13.0-rc/apache/Dockerfile
  13.0-rc/apache/config/apache-pretty-urls.config.php
  13.0-rc/apache/config/apcu.config.php
  13.0-rc/apache/config/apps.config.php
  13.0-rc/apache/config/autoconfig.php
  13.0-rc/apache/cron.sh
  13.0-rc/apache/entrypoint.sh
  13.0-rc/fpm-alpine/Dockerfile
  13.0-rc/fpm-alpine/config/apcu.config.php
  13.0-rc/fpm-alpine/config/apps.config.php
  13.0-rc/fpm-alpine/config/autoconfig.php
  13.0-rc/fpm-alpine/cron.sh
  13.0-rc/fpm-alpine/entrypoint.sh
  13.0-rc/fpm/Dockerfile
  13.0-rc/fpm/config/apcu.config.php
  13.0-rc/fpm/config/apps.config.php
  13.0-rc/fpm/config/autoconfig.php
  13.0-rc/fpm/cron.sh
  13.0-rc/fpm/entrypoint.sh
Labels: bug, image

#284 Make container scripts posix compliant
  11.0/apache/cron.sh
  11.0/apache/entrypoint.sh
  11.0/fpm-alpine/Dockerfile
  11.0/fpm-alpine/cron.sh
  11.0/fpm-alpine/entrypoint.sh
  11.0/fpm/cron.sh
  11.0/fpm/entrypoint.sh
  12.0/apache/cron.sh
  12.0/apache/entrypoint.sh
  12.0/fpm-alpine/Dockerfile
  12.0/fpm-alpine/cron.sh
  12.0/fpm-alpine/entrypoint.sh
  12.0/fpm/cron.sh
  12.0/fpm/entrypoint.sh
  13.0/apache/cron.sh
  13.0/apache/entrypoint.sh
  13.0/fpm-alpine/Dockerfile
  13.0/fpm-alpine/cron.sh
  13.0/fpm-alpine/entrypoint.sh
  13.0/fpm/cron.sh
  13.0/fpm/entrypoint.sh
  Dockerfile-alpine.template
  docker-cron.sh
  docker-entrypoint.sh
Labels: bug, enhancement, image

#289 Add tags for the release channels
  generate-stackbrew-library.sh
Labels: enhancement, image

#258 Fix Transaction Isolation Level of MYSQL Databases in .example section
  .examples/docker-compose/insecure/mariadb-cron-redis/apache/db/Dockerfile
  .examples/docker-compose/insecure/mariadb-cron-redis/apache/db/transaction-isolation.conf
  .examples/docker-compose/insecure/mariadb-cron-redis/apache/docker-compose.yml
  .examples/docker-compose/insecure/mariadb-cron-redis/fpm/db/Dockerfile
  .examples/docker-compose/insecure/mariadb-cron-redis/fpm/db/transaction-isolation.conf
  .examples/docker-compose/insecure/mariadb-cron-redis/fpm/docker-compose.yml
  .examples/docker-compose/insecure/mariadb/apache/db/Dockerfile
  .examples/docker-compose/insecure/mariadb/apache/db/transaction-isolation.conf
  .examples/docker-compose/insecure/mariadb/apache/docker-compose.yml
  .examples/docker-compose/insecure/mariadb/fpm/db/Dockerfile
  .examples/docker-compose/insecure/mariadb/fpm/db/transaction-isolation.conf
  .examples/docker-compose/insecure/mariadb/fpm/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/db/Dockerfile
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/db/transaction-isolation.conf
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/db/Dockerfile
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/db/transaction-isolation.conf
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb/apache/db/Dockerfile
  .examples/docker-compose/with-nginx-proxy/mariadb/apache/db/transaction-isolation.conf
  .examples/docker-compose/with-nginx-proxy/mariadb/apache/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb/fpm/db/Dockerfile
  .examples/docker-compose/with-nginx-proxy/mariadb/fpm/db/transaction-isolation.conf
  .examples/docker-compose/with-nginx-proxy/mariadb/fpm/docker-compose.yml
Labels: enhancement, examples

#183 fix #176 Request Entity Too Large
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb/apache/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb/fpm/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/postgres/apache/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/postgres/fpm/docker-compose.yml
Labels: bug, examples
