Repository nextcloud/docker, pull requests merged in 2018-06, with the labels that each got.

#344 Fix a race condition caused by the gpg-agent
  12.0/apache/Dockerfile
  12.0/fpm-alpine/Dockerfile
  12.0/fpm/Dockerfile
  13.0/apache/Dockerfile
  13.0/fpm-alpine/Dockerfile
  13.0/fpm/Dockerfile
  Dockerfile-alpine.template
  Dockerfile-debian.template
Labels: bug, image

#355 Do "pecl install" in series so it fails properly
  12.0-rc/apache/Dockerfile
  12.0-rc/fpm-alpine/Dockerfile
  12.0-rc/fpm/Dockerfile
  12.0/apache/Dockerfile
  12.0/fpm-alpine/Dockerfile
  12.0/fpm/Dockerfile
  13.0-rc/apache/Dockerfile
  13.0-rc/fpm-alpine/Dockerfile
  13.0-rc/fpm/Dockerfile
  13.0/apache/Dockerfile
  13.0/fpm-alpine/Dockerfile
  13.0/fpm/Dockerfile
  Dockerfile-alpine.template
  Dockerfile-debian.template
Labels: enhancement, image

#357 Kill the gpg-agent
  12.0-rc/apache/Dockerfile
  12.0-rc/fpm-alpine/Dockerfile
  12.0-rc/fpm/Dockerfile
  12.0/apache/Dockerfile
  12.0/fpm-alpine/Dockerfile
  12.0/fpm/Dockerfile
  13.0-rc/apache/Dockerfile
  13.0-rc/fpm-alpine/Dockerfile
  13.0-rc/fpm/Dockerfile
  13.0/apache/Dockerfile
  13.0/fpm-alpine/Dockerfile
  13.0/fpm/Dockerfile
  Dockerfile-alpine.template
  Dockerfile-debian.template
Labels: bug, image

#358 Adjust gpg code to kill daemons, cutting down on race conditions
  12.0-rc/apache/Dockerfile
  12.0-rc/fpm-alpine/Dockerfile
  12.0-rc/fpm/Dockerfile
  12.0/apache/Dockerfile
  12.0/fpm-alpine/Dockerfile
  12.0/fpm/Dockerfile
  13.0-rc/apache/Dockerfile
  13.0-rc/fpm-alpine/Dockerfile
  13.0-rc/fpm/Dockerfile
  13.0/apache/Dockerfile
  13.0/fpm-alpine/Dockerfile
  13.0/fpm/Dockerfile
  Dockerfile-alpine.template
  Dockerfile-debian.template
Labels: bug, image

#363 Ship 13.0.3 on stable channel
  .travis.yml
  12.0-rc/apache/Dockerfile
  12.0-rc/apache/config/apache-pretty-urls.config.php
  12.0-rc/apache/config/apcu.config.php
  12.0-rc/apache/config/apps.config.php
  12.0-rc/apache/config/autoconfig.php
  12.0-rc/apache/cron.sh
  12.0-rc/apache/entrypoint.sh
  12.0-rc/fpm-alpine/Dockerfile
  12.0-rc/fpm-alpine/config/apcu.config.php
  12.0-rc/fpm-alpine/config/apps.config.php
  12.0-rc/fpm-alpine/config/autoconfig.php
  12.0-rc/fpm-alpine/cron.sh
  12.0-rc/fpm-alpine/entrypoint.sh
  12.0-rc/fpm/Dockerfile
  12.0-rc/fpm/config/apcu.config.php
  12.0-rc/fpm/config/apps.config.php
  12.0-rc/fpm/config/autoconfig.php
  12.0-rc/fpm/cron.sh
  12.0-rc/fpm/entrypoint.sh
  12.0/apache/Dockerfile
  12.0/fpm-alpine/Dockerfile
  12.0/fpm/Dockerfile
  13.0-rc/apache/Dockerfile
  13.0-rc/apache/config/apache-pretty-urls.config.php
  13.0-rc/apache/config/apcu.config.php
  13.0-rc/apache/config/apps.config.php
  13.0-rc/apache/config/autoconfig.php
  13.0-rc/apache/cron.sh
  13.0-rc/apache/entrypoint.sh
  13.0-rc/fpm-alpine/Dockerfile
  13.0-rc/fpm-alpine/config/apcu.config.php
  13.0-rc/fpm-alpine/config/apps.config.php
  13.0-rc/fpm-alpine/config/autoconfig.php
  13.0-rc/fpm-alpine/cron.sh
  13.0-rc/fpm-alpine/entrypoint.sh
  13.0-rc/fpm/Dockerfile
  13.0-rc/fpm/config/apcu.config.php
  13.0-rc/fpm/config/apps.config.php
  13.0-rc/fpm/config/autoconfig.php
  13.0-rc/fpm/cron.sh
  13.0-rc/fpm/entrypoint.sh
  13.0/apache/Dockerfile
  13.0/fpm-alpine/Dockerfile
  13.0/fpm/Dockerfile
  generate-stackbrew-library.sh
Labels: image

#366 Ship 13.0.4 on stable channel
  generate-stackbrew-library.sh
Labels: image

#370 Add pgp-happy-eyeballs to travis
  .travis.yml
Labels: enhancement
