Repository nextcloud/docker, pull requests merged in 2018-04, with the labels that each got.

#297 apache: set the remote ip from X-Real-IP by default
  11.0/apache/Dockerfile
  12.0/apache/Dockerfile
  13.0/apache/Dockerfile
  update.sh
Labels: enhancement, image

#303 Remove end of life version 11.0
  .travis.yml
  11.0/apache/Dockerfile
  11.0/apache/config/apache-pretty-urls.config.php
  11.0/apache/config/apcu.config.php
  11.0/apache/config/apps.config.php
  11.0/apache/config/autoconfig.php
  11.0/apache/cron.sh
  11.0/apache/entrypoint.sh
  11.0/fpm-alpine/Dockerfile
  11.0/fpm-alpine/config/apcu.config.php
  11.0/fpm-alpine/config/apps.config.php
  11.0/fpm-alpine/config/autoconfig.php
  11.0/fpm-alpine/cron.sh
  11.0/fpm-alpine/entrypoint.sh
  11.0/fpm/Dockerfile
  11.0/fpm/config/apcu.config.php
  11.0/fpm/config/apps.config.php
  11.0/fpm/config/autoconfig.php
  11.0/fpm/cron.sh
  11.0/fpm/entrypoint.sh
  update.sh
Labels: enhancement, image

#302 nginx: set the remote ip from X-Real-IP by default
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/web/nginx.conf
  .examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf
  .examples/docker-compose/with-nginx-proxy/postgres/fpm/web/nginx.conf
Labels: bug, examples

#307 Create a data dir outside the webroot.
  12.0/apache/Dockerfile
  12.0/fpm-alpine/Dockerfile
  12.0/fpm/Dockerfile
  13.0/apache/Dockerfile
  13.0/fpm-alpine/Dockerfile
  13.0/fpm/Dockerfile
  Dockerfile-alpine.template
  Dockerfile-debian.template
Labels: enhancement, image

#317 Changed db build to pre-existing image with command arguments
  .examples/docker-compose/insecure/mariadb-cron-redis/apache/db/Dockerfile
  .examples/docker-compose/insecure/mariadb-cron-redis/apache/db/transaction-isolation.conf
  .examples/docker-compose/insecure/mariadb-cron-redis/apache/docker-compose.yml
  .examples/docker-compose/insecure/mariadb-cron-redis/fpm/db/Dockerfile
  .examples/docker-compose/insecure/mariadb-cron-redis/fpm/db/transaction-isolation.conf
  .examples/docker-compose/insecure/mariadb-cron-redis/fpm/docker-compose.yml
  .examples/docker-compose/insecure/mariadb/apache/db/Dockerfile
  .examples/docker-compose/insecure/mariadb/apache/db/transaction-isolation.conf
  .examples/docker-compose/insecure/mariadb/apache/docker-compose.yml
  .examples/docker-compose/insecure/mariadb/fpm/db/Dockerfile
  .examples/docker-compose/insecure/mariadb/fpm/db/transaction-isolation.conf
  .examples/docker-compose/insecure/mariadb/fpm/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/db/Dockerfile
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/db/transaction-isolation.conf
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/db/Dockerfile
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/db/transaction-isolation.conf
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb/apache/db/Dockerfile
  .examples/docker-compose/with-nginx-proxy/mariadb/apache/db/transaction-isolation.conf
  .examples/docker-compose/with-nginx-proxy/mariadb/apache/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb/fpm/db/Dockerfile
  .examples/docker-compose/with-nginx-proxy/mariadb/fpm/db/transaction-isolation.conf
  .examples/docker-compose/with-nginx-proxy/mariadb/fpm/docker-compose.yml
Labels: enhancement, examples
