Repository nextcloud/docker, pull requests merged in 2018-08, with the labels that each got.

#406 Small cleanups
  .examples/README.md
  .examples/docker-compose/insecure/mariadb-cron-redis/apache/docker-compose.yml
  .examples/docker-compose/insecure/mariadb-cron-redis/fpm/docker-compose.yml
  .examples/docker-compose/insecure/mariadb/apache/docker-compose.yml
  .examples/docker-compose/insecure/mariadb/fpm/docker-compose.yml
  .examples/docker-compose/insecure/postgres/apache/docker-compose.yml
  .examples/docker-compose/insecure/postgres/fpm/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb/apache/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb/fpm/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/postgres/apache/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/postgres/fpm/docker-compose.yml
  .travis/test-example-dockerfiles.sh
  12.0/apache/entrypoint.sh
  12.0/fpm-alpine/entrypoint.sh
  12.0/fpm/entrypoint.sh
  13.0/apache/entrypoint.sh
  13.0/fpm-alpine/entrypoint.sh
  13.0/fpm/entrypoint.sh
  14.0-beta/apache/entrypoint.sh
  14.0-beta/fpm-alpine/entrypoint.sh
  14.0-beta/fpm/entrypoint.sh
  README.md
  docker-entrypoint.sh
  update.sh
Labels: enhancement

#414 Fix full Dockerfile example
  .examples/dockerfiles/full/apache/Dockerfile
  .examples/dockerfiles/full/fpm/Dockerfile
Labels: bug, examples

#413 Enable apcu for cli calls
  12.0/apache/Dockerfile
  12.0/fpm-alpine/Dockerfile
  12.0/fpm/Dockerfile
  13.0/apache/Dockerfile
  13.0/fpm-alpine/Dockerfile
  13.0/fpm/Dockerfile
  14.0-beta/apache/Dockerfile
  14.0-beta/fpm-alpine/Dockerfile
  14.0-beta/fpm/Dockerfile
  Dockerfile-alpine.template
  Dockerfile-debian.template
Labels: bug, image

#416 Switch to php 7.2 for nextcloud 13.0 and greater
  12.0/apache/Dockerfile
  12.0/fpm-alpine/Dockerfile
  12.0/fpm/Dockerfile
  13.0/apache/Dockerfile
  13.0/fpm-alpine/Dockerfile
  13.0/fpm/Dockerfile
  14.0-beta/apache/Dockerfile
  14.0-beta/fpm-alpine/Dockerfile
  14.0-beta/fpm/Dockerfile
  Dockerfile-alpine.template
  Dockerfile-debian.template
  update.sh
Labels: enhancement, image

#418 Update redis to version 4.1.1
  12.0/apache/Dockerfile
  12.0/fpm-alpine/Dockerfile
  12.0/fpm/Dockerfile
  13.0/apache/Dockerfile
  13.0/fpm-alpine/Dockerfile
  13.0/fpm/Dockerfile
  14.0-beta/apache/Dockerfile
  14.0-beta/fpm-alpine/Dockerfile
  14.0-beta/fpm/Dockerfile
  update.sh
Labels: enhancement, image

#423 Use $request_uri instead of $uri in nginx config
  .examples/docker-compose/insecure/mariadb-cron-redis/fpm/web/nginx.conf
  .examples/docker-compose/insecure/mariadb/fpm/web/nginx.conf
  .examples/docker-compose/insecure/postgres/fpm/web/nginx.conf
  .examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm/web/nginx.conf
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/web/nginx.conf
  .examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf
  .examples/docker-compose/with-nginx-proxy/postgres/fpm/web/nginx.conf
Labels: bug, examples

#424 Remove the "--no-app-disable" option form the "occ upgrade" command
  12.0/apache/entrypoint.sh
  12.0/fpm-alpine/entrypoint.sh
  12.0/fpm/entrypoint.sh
  13.0/apache/entrypoint.sh
  13.0/fpm-alpine/entrypoint.sh
  13.0/fpm/entrypoint.sh
  14.0-beta/apache/entrypoint.sh
  14.0-beta/fpm-alpine/entrypoint.sh
  14.0-beta/fpm/entrypoint.sh
  docker-entrypoint.sh
Labels: bug, image

#433 Remove duplicated var from example
  .examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm/db.env
Labels: enhancement, examples

#437 example Dockerfiles: remove obsolete jessie backports
  .examples/dockerfiles/full/apache/Dockerfile
  .examples/dockerfiles/full/fpm/Dockerfile
Labels: enhancement, examples

#439 Upgrade to alpine 3.8
  12.0-rc/fpm-alpine/Dockerfile
  12.0/fpm-alpine/Dockerfile
  13.0-rc/fpm-alpine/Dockerfile
  13.0/fpm-alpine/Dockerfile
  14.0-rc/fpm-alpine/Dockerfile
  Dockerfile-alpine.template
Labels: enhancement, image
