Repository nextcloud/docker, pull requests merged in 2019-03, with the labels that each got.

#688 Add image for alpha
  .travis.yml
  16.0-alpha/apache/Dockerfile
  16.0-alpha/apache/config/apache-pretty-urls.config.php
  16.0-alpha/apache/config/apcu.config.php
  16.0-alpha/apache/config/apps.config.php
  16.0-alpha/apache/config/autoconfig.php
  16.0-alpha/apache/config/redis.config.php
  16.0-alpha/apache/cron.sh
  16.0-alpha/apache/entrypoint.sh
  16.0-alpha/apache/upgrade.exclude
  16.0-alpha/fpm-alpine/Dockerfile
  16.0-alpha/fpm-alpine/config/apcu.config.php
  16.0-alpha/fpm-alpine/config/apps.config.php
  16.0-alpha/fpm-alpine/config/autoconfig.php
  16.0-alpha/fpm-alpine/config/redis.config.php
  16.0-alpha/fpm-alpine/cron.sh
  16.0-alpha/fpm-alpine/entrypoint.sh
  16.0-alpha/fpm-alpine/upgrade.exclude
  16.0-alpha/fpm/Dockerfile
  16.0-alpha/fpm/config/apcu.config.php
  16.0-alpha/fpm/config/apps.config.php
  16.0-alpha/fpm/config/autoconfig.php
  16.0-alpha/fpm/config/redis.config.php
  16.0-alpha/fpm/cron.sh
  16.0-alpha/fpm/entrypoint.sh
  16.0-alpha/fpm/upgrade.exclude
  generate-stackbrew-library.sh
  update.sh
Labels: enhancement, image

#660 Copy version.php last
  13.0/apache/entrypoint.sh
  13.0/apache/upgrade.exclude
  13.0/fpm-alpine/entrypoint.sh
  13.0/fpm-alpine/upgrade.exclude
  13.0/fpm/entrypoint.sh
  13.0/fpm/upgrade.exclude
  14.0/apache/entrypoint.sh
  14.0/apache/upgrade.exclude
  14.0/fpm-alpine/entrypoint.sh
  14.0/fpm-alpine/upgrade.exclude
  14.0/fpm/entrypoint.sh
  14.0/fpm/upgrade.exclude
  15.0/apache/entrypoint.sh
  15.0/apache/upgrade.exclude
  15.0/fpm-alpine/entrypoint.sh
  15.0/fpm-alpine/upgrade.exclude
  15.0/fpm/entrypoint.sh
  15.0/fpm/upgrade.exclude
  16.0-alpha/apache/entrypoint.sh
  16.0-alpha/apache/upgrade.exclude
  16.0-alpha/fpm-alpine/entrypoint.sh
  16.0-alpha/fpm-alpine/upgrade.exclude
  16.0-alpha/fpm/entrypoint.sh
  16.0-alpha/fpm/upgrade.exclude
  docker-entrypoint.sh
  upgrade.exclude
Labels: bug, image

#543 Update pecl extensions in update.sh
  13.0/apache/Dockerfile
  13.0/fpm-alpine/Dockerfile
  13.0/fpm/Dockerfile
  14.0/apache/Dockerfile
  14.0/fpm-alpine/Dockerfile
  14.0/fpm/Dockerfile
  15.0/apache/Dockerfile
  15.0/fpm-alpine/Dockerfile
  15.0/fpm/Dockerfile
  16.0-alpha/apache/Dockerfile
  16.0-alpha/fpm-alpine/Dockerfile
  16.0-alpha/fpm/Dockerfile
  update.sh
Labels: enhancement

#692 Also remove alphas
  update.sh
Labels: bug
