Repository nextcloud/docker, pull requests merged in 2019-02, with the labels that each got.

#600 Set Redis through environment variables
  .config/redis.config.php
  .examples/docker-compose/insecure/mariadb-cron-redis/apache/app/redis.config.php
  .examples/docker-compose/insecure/mariadb-cron-redis/apache/docker-compose.yml
  .examples/docker-compose/insecure/mariadb-cron-redis/fpm/app/redis.config.php
  .examples/docker-compose/insecure/mariadb-cron-redis/fpm/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/app/redis.config.php
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/app/redis.config.php
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml
  13.0/apache/config/redis.config.php
  13.0/fpm-alpine/config/redis.config.php
  13.0/fpm/config/redis.config.php
  14.0/apache/config/redis.config.php
  14.0/fpm-alpine/config/redis.config.php
  14.0/fpm/config/redis.config.php
  15.0/apache/config/redis.config.php
  15.0/fpm-alpine/config/redis.config.php
  15.0/fpm/config/redis.config.php
  README.md
Labels: enhancement, image

#639 Remove app dockerfile
  .examples/docker-compose/insecure/mariadb-cron-redis/apache/app/Dockerfile
  .examples/docker-compose/insecure/mariadb-cron-redis/apache/docker-compose.yml
  .examples/docker-compose/insecure/mariadb-cron-redis/fpm/app/Dockerfile
  .examples/docker-compose/insecure/mariadb-cron-redis/fpm/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/app/Dockerfile
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/docker-compose.yml
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/app/Dockerfile
  .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml
Labels: bug, examples

#641 Update release channels
  generate-stackbrew-library.sh
Labels: image

#640 Update to Alpine 3.9
  13.0/fpm-alpine/Dockerfile
  14.0/fpm-alpine/Dockerfile
  15.0/fpm-alpine/Dockerfile
  Dockerfile-alpine.template
Labels: image

#661 Ship 15.0.4 on production channel
  generate-stackbrew-library.sh
Labels: image

#663 Ship 15.0.4 on production and stable channel
  generate-stackbrew-library.sh
Labels: image
