Repository nextcloud/docker, pull requests merged in 2022-04, with the labels that each got.

#1698 Prevent nginx HTTP Server Detection
  .examples/docker-compose/insecure/mariadb/fpm/web/nginx.conf
  .examples/docker-compose/insecure/postgres/fpm/web/nginx.conf
  .examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf
  .examples/docker-compose/with-nginx-proxy/postgres/fpm/web/nginx.conf
Labels: upstream

#1730 Add mandatory summary step for branches protection
  .github/workflows/images.yml
Labels: enhancement

#1684 Add healthcheck
  Dockerfile-alpine.template
  Dockerfile-debian.template
Labels: enhancement

#1732 Revert "Add healthcheck"
  Dockerfile-alpine.template
  Dockerfile-debian.template
Labels: bug

#1728 Allow simultaneous initialization of common html volume
  docker-entrypoint.sh
  upgrade.exclude
Labels: enhancement
